/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux linux 2.6.27.5-117.fc10.i686.PAE #1 SMP Tue Nov 18 12:08:10 EST 2008 i686 i686 i386 GNU/Linux"
#define BUILD_ENV_DATE "Wed Nov 27 10:17:18 CST 2013"
#define BUILD_ENV_SRCDIR "/disk2/antony/R7000/GPL/V1.0.2.164/V1.0.2.164_1.0.15/ap/gpl/samba-3.0.25b/source"
#define BUILD_ENV_BUILDDIR "/disk2/antony/R7000/GPL/V1.0.2.164/V1.0.2.164_1.0.15/ap/gpl/samba-3.0.25b/source"
#define BUILD_ENV_USER "antony"
#define BUILD_ENV_HOST "linux"
#define BUILD_ENV_COMPILER "arm-brcm-linux-uclibcgnueabi-gcc"
#endif /* _BUILD_ENV_H */
